### ISSUE TITLE
Provide workflow in ReadMe.md

### ISSUE THREAD

**Issue by thejones** [davewilton/generator-typescript-wab-widget#1]
What is your workflow for using this? I am most curious in if/how you are syncing the application in stemapp & app directories, etc. Just looking for some general idea on how you are going about this. 

Thanks.

**Comment by davewilton** [comment]
Good point @thejones . This app doesn't make any attempt to deal with workflow. We ( @gavinr ) are thinking about merging these templates into the esri builder which does attempt to deal with workflow. It uses a grunt task to copy the files over, which perhaps could be modified.

https://github.com/Esri/generator-esri-appbuilder-js

Internally we don't tend to follow this best practise and actually just take a copy of the generated wab site from the server folder and use that with a local dev server

**Comment by gavinr** [comment]
As a path forward to [eventually get TypeScript option into that generator](https://github.com/Esri/generator-esri-appbuilder-js/issues/61), @davewilton helped me build this repository which demonstrates what the Generator would output: https://github.com/gavinr/web-appbuilder-typescript-examples (see the `builder` example folder specifically).

Please take a look, see if that workflow works for you, and let me know what feedback you have, either in that repository, or if you have general thoughts of getting Typescript into the generator, you can comment [here](https://github.com/Esri/generator-esri-appbuilder-js/issues/61). Thank you both!!

**Comment by davewilton** [comment]
Merged into esri app builder
